// Copyright 2026 Vivek Negi. Licensed under the Elastic License 2.0 (ELv2).
// See LICENSE in the project root for license information.

/**
 * W6.T4 — `create-shopverse-plugin` scaffolder (plan §7).
 *
 * Emits a minimal plugin skeleton modelled on
 * `backend/plugins/hello-world/`. The scaffold ships a NestJS
 * DynamicModule with a Bootstrap provider, a placeholder hook
 * subscription, and a placeholder event subscription. Optional
 * flags add a frontend slot scaffold and an empty Prisma schema
 * file.
 *
 * The scaffolder is filesystem-only; it does not run npm install
 * or modify `backend/plugins.config.ts`. The "next steps" output
 * tells the operator to do those manually — explicit beats
 * automated when configuration is involved.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

export interface ScaffoldOptions {
  /** The plugin name (lowercase, alphanumeric + hyphens). */
  name: string;
  /** Repo root — directory whose children are `backend/`, `frontend/`, etc. */
  repoRoot: string;
  /** When true, write `frontend/src/plugins/<name>/Widget.tsx` + index. */
  withFrontend: boolean;
  /** When true, write an empty `prisma/schema/<name>.prisma`. */
  withSchema: boolean;
}

export interface ScaffoldResult {
  pluginId: string;
  filesWritten: string[];
  nextSteps: string[];
  warnings: string[];
}

const NAME_PATTERN = /^[a-z][a-z0-9-]*[a-z0-9]$/;

function validateName(name: string): string | null {
  if (name.length < 2) return 'name must be at least 2 characters';
  if (name.length > 40) return 'name must be ≤ 40 characters';
  if (!NAME_PATTERN.test(name)) {
    return 'name must be lowercase alphanumeric + hyphens, starting with a letter';
  }
  return null;
}

function toPascalCase(name: string): string {
  return name
    .split('-')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

interface FileSpec {
  relativePath: string;
  content: string;
}

function backendFiles(name: string, pascal: string, withSchema: boolean): FileSpec[] {
  const pkg = {
    name: `@shopverse/plugin-${name}`,
    version: '0.1.0-alpha.1',
    private: true,
    description: `ShopVerse plugin — ${name}.`,
    license: 'Elastic-2.0',
    main: 'dist/index.js',
    types: 'dist/index.d.ts',
    files: ['dist', 'README.md', 'LICENSE'],
    scripts: {
      build: 'tsc',
      clean: 'rimraf dist',
    },
    peerDependencies: {
      '@shopverse/sdk': '^0.1.0-alpha.1',
    },
    devDependencies: {
      '@shopverse/sdk': 'file:../../../packages/sdk',
      '@types/node': '^22.10.7',
      rimraf: '^6.0.1',
      typescript: '^5.7.3',
    },
  };

  const tsconfig = {
    compilerOptions: {
      module: 'commonjs',
      target: 'ES2021',
      lib: ['ES2021'],
      declaration: true,
      outDir: './dist',
      rootDir: './src',
      strict: true,
      esModuleInterop: true,
      experimentalDecorators: true,
      emitDecoratorMetadata: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
      resolveJsonModule: true,
      noUnusedLocals: true,
      noUnusedParameters: true,
      noImplicitReturns: true,
      noFallthroughCasesInSwitch: true,
    },
    include: ['src/**/*'],
    exclude: ['node_modules', 'dist', '**/*.spec.ts'],
  };

  const moduleSrc = `// Copyright 2026 <YOUR NAME>. Licensed under the Elastic License 2.0 (ELv2).

import { Injectable, Logger, Module, OnApplicationBootstrap } from '@nestjs/common';
import { HookRunner } from '../../../src/common/hook-runner.service';
import { EventBus } from '../../../src/common/event-bus.service';

const PLUGIN_ID = '@shopverse/plugin-${name}';

/**
 * ${pascal}PluginModule — TODO: describe what this plugin does.
 *
 * Generated by \`create-shopverse-plugin\`. See docs/plugins/guide.md
 * for the contract surface; tutorial.md for the 10-minute walkthrough.
 */
@Injectable()
class ${pascal}Bootstrap implements OnApplicationBootstrap {
  private readonly logger = new Logger('${pascal}');

  constructor(
    private readonly hooks: HookRunner,
    private readonly eventBus: EventBus,
  ) {}

  onApplicationBootstrap(): void {
    // TODO: replace this placeholder with a real hook subscription.
    // The full hook list is at docs/plugins/sdk-reference.md#hooks-5.
    this.hooks.register('cart.beforeReserve', PLUGIN_ID, async (ctx) => {
      this.logger.debug(\`cart.beforeReserve fired for user \${ctx.userId}\`);
      return undefined; // never reject from the placeholder
    });

    // TODO: replace this placeholder with a real event subscription.
    // The full event list is at docs/plugins/sdk-reference.md#events-12.
    this.eventBus.subscribe('order.placed', PLUGIN_ID, async (event) => {
      this.logger.debug(\`order.placed received: order #\${event.orderId}\`);
    });
  }
}

@Module({
  providers: [${pascal}Bootstrap],
})
export class ${pascal}PluginModule {}
`;

  const indexSrc = `// Copyright 2026 <YOUR NAME>. Licensed under the Elastic License 2.0 (ELv2).

export { ${pascal}PluginModule } from './${name}.module';
`;

  const readme = `# @shopverse/plugin-${name}

TODO: 1-paragraph description.

## What it does

TODO

## What it touches

- Hook: \`cart.beforeReserve\` (placeholder — replace)
- Event subscriber: \`order.placed\` (placeholder — replace)
${withSchema ? `- Database: \`prisma/schema/${name}.prisma\` (empty starter)` : ''}

## Configuration

Add to \`backend/plugins.config.ts\`:

\`\`\`ts
{
  id: '@shopverse/plugin-${name}',
  source: 'workspace',
  workspacePath: './plugins/${name}/src',
  enabled: true,
},
\`\`\`

## Development

\`\`\`bash
cd backend && npx tsc --noEmit       # type check
cd backend && npm run start:dev      # dev server with HMR
\`\`\`

See \`docs/plugins/guide.md\` for the full author guide and
\`docs/plugins/sdk-reference.md\` for every contract type.
`;

  const files: FileSpec[] = [
    {
      relativePath: `backend/plugins/${name}/package.json`,
      content: JSON.stringify(pkg, null, 2) + '\n',
    },
    {
      relativePath: `backend/plugins/${name}/tsconfig.json`,
      content: JSON.stringify(tsconfig, null, 2) + '\n',
    },
    {
      relativePath: `backend/plugins/${name}/src/${name}.module.ts`,
      content: moduleSrc,
    },
    {
      relativePath: `backend/plugins/${name}/src/index.ts`,
      content: indexSrc,
    },
    {
      relativePath: `backend/plugins/${name}/README.md`,
      content: readme,
    },
  ];

  if (withSchema) {
    files.push({
      relativePath: `prisma/schema/${name}.prisma`,
      content: `// @shopverse/plugin-${name}
//
// Plugin-owned models live in this file. Per docs/plugins/database.md:
// - NEW plugins MUST NOT add FKs to kernel tables. Use a defensive
//   userId Int (not a relation) + a user.beforeDelete hook in the
//   plugin module to delete linked rows on user deletion.
// - Plugin migrations run AFTER kernel migrations in the order
//   declared in plugins.config.ts.

// model My${toPascalCase(name)}Row {
//   id        Int      @id @default(autoincrement())
//   createdAt DateTime @default(now())
// }
`,
    });
  }

  return files;
}

function frontendFiles(name: string, pascal: string): FileSpec[] {
  const widgetSrc = `// Copyright 2026 <YOUR NAME>. Licensed under the Elastic License 2.0 (ELv2).

import { t } from '@shopverse/sdk-frontend';

/**
 * ${pascal}Widget — slot component for \`@shopverse/plugin-${name}\`.
 * Generated stub. Replace with your plugin's UI.
 */
export function ${pascal}Widget({ productId }: { productId: number }) {
  return (
    <div className="text-sm text-slate-600 mt-2">
      {t('${name}.placeholder', \`${pascal} widget on product #\${productId}\`)}
    </div>
  );
}

export default ${pascal}Widget;
`;

  const indexSrc = `// Copyright 2026 <YOUR NAME>. Licensed under the Elastic License 2.0 (ELv2).

import type { SlotRegistration } from '@/lib/slots';
import { ${pascal}Widget } from './${pascal}Widget';

/**
 * \`@shopverse/plugin-${name}\` frontend registrations.
 *
 * Wire into \`frontend/src/generated/slot-registrations.ts\` by adding:
 *
 *   import { slots as ${toCamelCase(name)}Slots } from '@/plugins/${name}';
 *   // ...
 *   export const ALL_PLUGIN_SLOTS: SlotRegistration[] = [
 *     ...existing,
 *     ...${toCamelCase(name)}Slots,
 *   ];
 *
 * See docs/plugins/slots.md for the full slot taxonomy.
 */
export const slots: SlotRegistration[] = [
  {
    pluginId: '@shopverse/plugin-${name}',
    name: 'pdp.afterDescription',
    component: ${pascal}Widget as never,
    minHeight: 32,
  },
];

export { ${pascal}Widget };
`;

  return [
    {
      relativePath: `frontend/src/plugins/${name}/${pascal}Widget.tsx`,
      content: widgetSrc,
    },
    {
      relativePath: `frontend/src/plugins/${name}/index.ts`,
      content: indexSrc,
    },
  ];
}

function toCamelCase(name: string): string {
  const parts = name.split('-').filter(Boolean);
  return (
    parts[0] +
    parts
      .slice(1)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join('')
  );
}

export function scaffold(opts: ScaffoldOptions): ScaffoldResult {
  const err = validateName(opts.name);
  if (err) {
    throw new Error(`[create-shopverse-plugin] invalid name: ${err}`);
  }
  const pluginId = `@shopverse/plugin-${opts.name}`;
  const pascal = toPascalCase(opts.name);

  // Refuse to clobber existing directories — operators who really
  // want to overwrite should rm -rf first.
  const backendDir = path.join(opts.repoRoot, 'backend', 'plugins', opts.name);
  if (fs.existsSync(backendDir)) {
    throw new Error(
      `[create-shopverse-plugin] backend/plugins/${opts.name}/ already exists — refusing to overwrite`,
    );
  }
  const frontendDir = path.join(opts.repoRoot, 'frontend', 'src', 'plugins', opts.name);
  if (opts.withFrontend && fs.existsSync(frontendDir)) {
    throw new Error(
      `[create-shopverse-plugin] frontend/src/plugins/${opts.name}/ already exists — refusing to overwrite`,
    );
  }
  const schemaFile = path.join(opts.repoRoot, 'prisma', 'schema', `${opts.name}.prisma`);
  if (opts.withSchema && fs.existsSync(schemaFile)) {
    throw new Error(
      `[create-shopverse-plugin] prisma/schema/${opts.name}.prisma already exists — refusing to overwrite`,
    );
  }

  const files: FileSpec[] = [];
  files.push(...backendFiles(opts.name, pascal, opts.withSchema));
  if (opts.withFrontend) {
    files.push(...frontendFiles(opts.name, pascal));
  }

  const written: string[] = [];
  for (const f of files) {
    const abs = path.join(opts.repoRoot, f.relativePath);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, f.content);
    written.push(f.relativePath);
  }

  const nextSteps: string[] = [
    `cd backend/plugins/${opts.name} && npm install`,
    `Add the entry to backend/plugins.config.ts (see backend/plugins/${opts.name}/README.md)`,
  ];
  if (opts.withFrontend) {
    nextSteps.push(
      `Wire slots into frontend/src/generated/slot-registrations.ts (see frontend/src/plugins/${opts.name}/index.ts)`,
    );
  }
  if (opts.withSchema) {
    nextSteps.push(
      `Define your models in prisma/schema/${opts.name}.prisma + run \`npx prisma migrate dev --schema prisma/schema --name ${opts.name}-init\``,
    );
  }
  nextSteps.push(`cd backend && npx tsc --noEmit  # confirm the build is green`);

  const warnings: string[] = [];
  if (opts.withSchema && !fs.existsSync(path.join(opts.repoRoot, 'prisma', 'schema'))) {
    warnings.push(
      `prisma/schema/ does not exist — the scaffolder created it, but verify this is intentional.`,
    );
  }

  return { pluginId, filesWritten: written, nextSteps, warnings };
}
