apiVersion: v1
kind: Service
metadata:
  name: shopverse-backend
  namespace: ${NAMESPACE}
  labels:
    app.kubernetes.io/name: shopverse
    app.kubernetes.io/instance: shopverse
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: shopverse
    app.kubernetes.io/instance: shopverse
    app.kubernetes.io/component: backend
