-- AlterTable
ALTER TABLE "StoreSettings" ADD COLUMN     "freeShippingThreshold" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "shippingFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "taxRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

