// Copyright 2026 Vivek Negi. Licensed under the Business Source License 1.1 (BSL).
// See LICENSE in the project root for license information.

/**
 * `create-shopverse-store` scaffolder (plan §7 — DX / 0-to-store).
 *
 * ShopVerse is a full application you clone, not a library you import —
 * so this scaffolder does NOT emit app code. It configures an already-
 * cloned repo for ONE market: it writes the env files (with the real
 * variable names the app boots with), a `store.config.json` mirroring the
 * `StoreSettings` singleton, and — on request — Railway / Render deploy
 * blueprints with the store's currency baked in.
 *
 * It is filesystem-only: it never runs `npm install`, never touches the
 * database, and refuses to overwrite an existing env / config file (those
 * may hold real secrets). Secrets the operator must supply (Stripe keys,
 * DATABASE_URL) are emitted as explicit `REPLACE_ME` placeholders;
 * `JWT_SECRET` is generated so the backend boots immediately in dev.
 */

import * as crypto from 'node:crypto';
import * as fs from 'node:fs';
import * as path from 'node:path';

export interface ScaffoldStoreOptions {
  /** Store display name (e.g. "Acme Outfitters"). */
  name: string;
  /** Repo root — directory whose children are `backend/`, `frontend/`, etc. */
  repoRoot: string;
  /** ISO 4217 currency code (e.g. USD, EUR, INR, JPY). */
  currency: string;
  /** ISO 3166-1 alpha-2 country code (e.g. US, IN, GB). */
  country: string;
  /** BCP 47 locale (e.g. en-US, en-IN, de-DE). */
  locale: string;
  /** Region-pack id label (e.g. 'india', 'us'); '' = store-config defaults, no pack. */
  region: string;
  /** Default tax rate as a fraction (0.18 = 18%); ignored when a TaxStrategy pack is enabled. */
  taxRate: number;
  /** Free-shipping threshold in major currency units (0 = none). */
  freeShippingThreshold: number;
  /** Flat shipping fee in major currency units (0 = free). */
  shippingFee: number;
  /** White-label: sets NEXT_PUBLIC_HIDE_POWERED_BY (only with a commercial license). */
  hideBadge: boolean;
  /** Emit `railway.json` (backend service blueprint). */
  withRailway: boolean;
  /** Emit `render.yaml` (full Render blueprint: db + api + web). */
  withRender: boolean;
  /** Secret generator — injectable so tests are deterministic. */
  generateSecret?: () => string;
}

export interface ScaffoldStoreResult {
  storeName: string;
  slug: string;
  filesWritten: string[];
  nextSteps: string[];
  warnings: string[];
}

interface FileSpec {
  relativePath: string;
  content: string;
}

const CURRENCY_PATTERN = /^[A-Z]{3}$/;
const COUNTRY_PATTERN = /^[A-Z]{2}$/;
const LOCALE_PATTERN = /^[a-z]{2,3}(-[A-Za-z0-9]{2,8})*$/i;

function validate(opts: ScaffoldStoreOptions): string | null {
  const n = opts.name.trim();
  if (n.length < 2) return 'name must be at least 2 characters';
  if (opts.name.length > 60) return 'name must be ≤ 60 characters';
  if (!/[a-zA-Z0-9]/.test(opts.name)) return 'name must contain at least one letter or digit';
  if (!CURRENCY_PATTERN.test(opts.currency)) return `currency must be a 3-letter ISO 4217 code (got "${opts.currency}")`;
  if (!COUNTRY_PATTERN.test(opts.country)) return `country must be a 2-letter ISO 3166-1 code (got "${opts.country}")`;
  if (!LOCALE_PATTERN.test(opts.locale)) return `locale must be a BCP 47 tag like en-US (got "${opts.locale}")`;
  if (!(opts.taxRate >= 0 && opts.taxRate <= 1)) return 'taxRate must be a fraction between 0 and 1 (0.18 = 18%)';
  if (!(opts.freeShippingThreshold >= 0)) return 'freeShippingThreshold must be ≥ 0';
  if (!(opts.shippingFee >= 0)) return 'shippingFee must be ≥ 0';
  return null;
}

/** Lowercase, hyphen-separated slug derived from the store name. */
export function slugify(name: string): string {
  const s = name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40)
    .replace(/-+$/g, '');
  return s || 'store';
}

function defaultSecret(): string {
  // 36 random bytes → 48 url-safe chars, comfortably over the backend's
  // 32-char JWT_SECRET minimum (auth.module.ts) so the app boots in dev.
  return crypto.randomBytes(36).toString('base64url');
}

function backendEnv(opts: ScaffoldStoreOptions, slug: string, jwtSecret: string): string {
  return `# ShopVerse backend env — ${opts.name}
# Generated by create-shopverse-store. Fill in every REPLACE_ME before
# going to production. This file is gitignored — never commit real secrets.

# ── Required (the app refuses to boot without these — see main.ts) ──
DATABASE_URL="postgresql://USER:PASSWORD@localhost:5432/shopverse?schema=public"
JWT_SECRET="${jwtSecret}"
STRIPE_SECRET_KEY="sk_test_REPLACE_ME"
STRIPE_WEBHOOK_SECRET="whsec_REPLACE_ME"

# ── Required in production only ──
# CORS_ORIGIN="https://${slug}.example.com"

# ── Server ──
PORT=4000
NODE_ENV=development

# ── Background workers + cache (optional; in-process fallback if unset) ──
# REDIS_URL="redis://localhost:6379"
# DISABLE_WORKERS=false

# ── Seed admin (optional — prisma seed defaults to admin@store.com if unset) ──
# SEED_ADMIN_EMAIL="admin@${slug}.com"
# SEED_ADMIN_PASSWORD="ChangeMe@StrongPassword1"

# ── Observability (optional) ──
# SENTRY_DSN=
# OTEL_EXPORTER_OTLP_ENDPOINT=
OTEL_SERVICE_NAME="${slug}-backend"

# ── Swagger basic-auth in production (optional) ──
# SWAGGER_USER=
# SWAGGER_PASS=
`;
}

function frontendEnv(opts: ScaffoldStoreOptions): string {
  return `# ShopVerse frontend env — ${opts.name}
# Generated by create-shopverse-store. NEXT_PUBLIC_* values are baked into
# the client bundle at build time, so rebuild after changing them.

# ── Store identity ──
NEXT_PUBLIC_STORE_CURRENCY=${opts.currency}
NEXT_PUBLIC_STORE_LOCALE=${opts.locale}

# ── API + site endpoints ──
NEXT_PUBLIC_API_URL=http://localhost:4000
NEXT_PUBLIC_BACKEND_URL=http://localhost:4000
NEXT_PUBLIC_SITE_URL=http://localhost:3000

# ── Stripe (publishable key is safe to expose) ──
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_REPLACE_ME

# ── "Powered by ShopVerse" badge ──
# Keeping the badge is required by the BSL Additional Use Grant on the free
# tier. Set to "true" ONLY with a commercial / white-label license.
NEXT_PUBLIC_HIDE_POWERED_BY=${opts.hideBadge ? 'true' : 'false'}

# ── Analytics (optional) ──
# NEXT_PUBLIC_POSTHOG_KEY=
# NEXT_PUBLIC_POSTHOG_HOST=
`;
}

function storeConfigJson(opts: ScaffoldStoreOptions, slug: string): string {
  const config = {
    $schema: 'https://shopverse.dev/schema/store.config.json',
    name: opts.name,
    slug,
    // Mirrors the StoreSettings singleton (id=1). Apply via the prisma seed
    // — see backend/src/prisma/seed.ts. region is null when no pack is used.
    storeSettings: {
      currency: opts.currency,
      country: opts.country,
      locale: opts.locale,
      region: opts.region || null,
      taxRate: opts.taxRate,
      freeShippingThreshold: opts.freeShippingThreshold,
      shippingFee: opts.shippingFee,
    },
  };
  return JSON.stringify(config, null, 2) + '\n';
}

function railwayJson(): string {
  // Railway railway.json is single-service strict JSON (no comments). This
  // configures the backend API; add the frontend as a second Railway service
  // pointing at frontend/Dockerfile. See STORE_SETUP.md.
  const config = {
    $schema: 'https://railway.app/railway.schema.json',
    build: {
      builder: 'DOCKERFILE',
      dockerfilePath: 'backend/Dockerfile',
    },
    deploy: {
      healthcheckPath: '/api/health',
      healthcheckTimeout: 100,
      restartPolicyType: 'ON_FAILURE',
      restartPolicyMaxRetries: 10,
    },
  };
  return JSON.stringify(config, null, 2) + '\n';
}

function renderYaml(opts: ScaffoldStoreOptions, slug: string): string {
  return `# Render Blueprint — ${opts.name} (ShopVerse)
# Spec: https://render.com/docs/blueprint-spec
# Review every value before deploying. Secrets marked "sync: false" must be
# set in the Render dashboard; they are intentionally not stored here.

databases:
  - name: ${slug}-db
    databaseName: shopverse
    plan: free

services:
  # ── Backend API ──
  - type: web
    name: ${slug}-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ${slug}-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false

  # ── Storefront (Next.js) ──
  - type: web
    name: ${slug}-web
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: .
    envVars:
      - key: NEXT_PUBLIC_STORE_CURRENCY
        value: ${opts.currency}
      - key: NEXT_PUBLIC_STORE_LOCALE
        value: ${opts.locale}
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_BACKEND_URL
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: NEXT_PUBLIC_HIDE_POWERED_BY
        value: "${opts.hideBadge ? 'true' : 'false'}"
`;
}

function storeSetupMd(opts: ScaffoldStoreOptions, slug: string, deploy: string[]): string {
  const deployLine =
    deploy.length > 0
      ? `\nDeploy blueprints emitted: ${deploy.join(', ')}. Review them, then connect the repo to your host.\n`
      : '';
  const regionLine = opts.region
    ? `\n> **Region pack:** enable \`@shopverse/plugin-${opts.region}\` in \`backend/plugins.config.ts\` so tax/locale for **${opts.country}** is exact.\n`
    : '';
  return `# Store Setup — ${opts.name}

Generated by \`create-shopverse-store\`. This store is configured for
**${opts.currency} / ${opts.country} / ${opts.locale}**.
${regionLine}
## 1. Install

\`\`\`bash
cd backend && npm install
cd ../frontend && npm install
npm install            # repo-root dev deps (hoisted test tooling)
\`\`\`

## 2. Secrets

Open \`backend/.env\` and \`frontend/.env.local\` and replace every
\`REPLACE_ME\`:

- \`DATABASE_URL\` — your Postgres connection string
- \`STRIPE_SECRET_KEY\` / \`STRIPE_WEBHOOK_SECRET\` — from the Stripe dashboard
- \`NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\` — Stripe publishable key

\`JWT_SECRET\` was generated for you (dev-ready). Rotate it for production.

## 3. Database + seed

The store identity lives in \`store.config.json\`. Apply it by editing the
\`StoreSettings\` block in \`backend/src/prisma/seed.ts\` to match, then:

\`\`\`bash
cd backend
npx prisma migrate deploy --schema prisma/schema
npx prisma db seed
\`\`\`

## 4. Run

\`\`\`bash
cd backend && npm run start:dev     # API on :4000 (/api)
cd frontend && npm run dev          # storefront on :3000
\`\`\`
${deployLine}
## Store config

\`\`\`json
${storeConfigJson(opts, slug).trimEnd()}
\`\`\`

See the [README](README.md) and \`docs/\` for the full operator guide.
`;
}

export function scaffold(opts: ScaffoldStoreOptions): ScaffoldStoreResult {
  const err = validate(opts);
  if (err) {
    throw new Error(`[create-shopverse-store] invalid options: ${err}`);
  }

  const slug = slugify(opts.name);
  const gen = opts.generateSecret ?? defaultSecret;

  // Targets we refuse to clobber (they may hold real secrets/config).
  const guarded: Array<[string, boolean]> = [
    ['backend/.env', true],
    ['frontend/.env.local', true],
    ['store.config.json', true],
    ['STORE_SETUP.md', true],
    ['railway.json', opts.withRailway],
    ['render.yaml', opts.withRender],
  ];
  for (const [rel, active] of guarded) {
    if (active && fs.existsSync(path.join(opts.repoRoot, rel))) {
      throw new Error(`[create-shopverse-store] ${rel} already exists — refusing to overwrite`);
    }
  }

  // Capture this BEFORE writing — writing backend/.env creates backend/,
  // which would otherwise mask a "wrong directory" mistake.
  const backendMissing = !fs.existsSync(path.join(opts.repoRoot, 'backend'));

  const jwtSecret = gen();
  const deployEmitted: string[] = [];
  const files: FileSpec[] = [
    { relativePath: 'backend/.env', content: backendEnv(opts, slug, jwtSecret) },
    { relativePath: 'frontend/.env.local', content: frontendEnv(opts) },
    { relativePath: 'store.config.json', content: storeConfigJson(opts, slug) },
  ];
  if (opts.withRailway) {
    files.push({ relativePath: 'railway.json', content: railwayJson() });
    deployEmitted.push('railway.json');
  }
  if (opts.withRender) {
    files.push({ relativePath: 'render.yaml', content: renderYaml(opts, slug) });
    deployEmitted.push('render.yaml');
  }
  files.push({ relativePath: 'STORE_SETUP.md', content: storeSetupMd(opts, slug, deployEmitted) });

  const written: string[] = [];
  for (const f of files) {
    const abs = path.join(opts.repoRoot, f.relativePath);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    fs.writeFileSync(abs, f.content);
    written.push(f.relativePath);
  }

  const nextSteps: string[] = [
    'Replace every REPLACE_ME in backend/.env + frontend/.env.local (Stripe keys, DATABASE_URL)',
    'Match the StoreSettings block in backend/src/prisma/seed.ts to store.config.json',
    'cd backend && npm install && npx prisma migrate deploy --schema prisma/schema && npx prisma db seed',
    'cd backend && npm run start:dev   # then cd frontend && npm run dev',
  ];
  if (opts.region) {
    nextSteps.push(`Enable @shopverse/plugin-${opts.region} in backend/plugins.config.ts for exact ${opts.country} tax/locale`);
  }
  if (deployEmitted.length > 0) {
    nextSteps.push(`Review ${deployEmitted.join(' + ')} and connect the repo to your host`);
  }
  nextSteps.push('Full checklist: STORE_SETUP.md');

  const warnings: string[] = [];
  if (backendMissing) {
    warnings.push('backend/ not found at repo root — run this from a cloned ShopVerse repo (or pass --repo-root).');
  }
  if (opts.hideBadge) {
    warnings.push('NEXT_PUBLIC_HIDE_POWERED_BY=true removes the badge — only valid with a commercial/white-label license.');
  }

  return { storeName: opts.name, slug, filesWritten: written, nextSteps, warnings };
}
